# Generated by Django 4.2.7 on 2023-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtaskmodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createtaskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
